apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "artists-website"
  title: "Artists Website"
  description: "Bakcstage Website example"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: group:default/goron-bowlers
  lifecycle: production
  system: artists-system
  dependsOn:
    - resource:default/artists-db
    - component:default/artists-backend
  consumesApis:
    - artist-apis
