apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-awesome-website"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: "group:default/hyrule-warriors"
  lifecycle: experimental
